// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQyopaw2I0d8-GzxFsh4kqb6lzbhqZ90',
    appId: '1:959510831103:web:9141cbab16abf6ce0fd1ca',
    messagingSenderId: '959510831103',
    projectId: 'todo-9860e',
    authDomain: 'todo-9860e.firebaseapp.com',
    storageBucket: 'todo-9860e.appspot.com',
    measurementId: 'G-94X1EH5532',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDym-qNFzYrvIRhFDFVaxCcHVgvi3kKU-w',
    appId: '1:959510831103:android:ebf224ffc81640ce0fd1ca',
    messagingSenderId: '959510831103',
    projectId: 'todo-9860e',
    storageBucket: 'todo-9860e.appspot.com',
  );
}
